[package]
name = "vulkan-sys"
version = "0.0.1-alpha.0"
description = "Low-level Vulkan bindings for Rust"
authors = ["Jacob R. Green"]
edition = "2021"
license-file = "LICENSE"

[dependencies]
thiserror = "1.0.29"
log = "0.4.21"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56.0", features = ["Win32_Foundation", "Win32_Security", "Win32_Graphics_Gdi"] }

[build-dependencies]
bindgen = "0.69.4"
